language: node_js
node_js:
 - "node"

cache:
  directories:
    - "node_modules"

sudo: required
addons:
  chrome: stable

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - pip install --user python-igraph
    
script:
 - ./run_tests.sh
    
