language: node_js
node_js:
 - "node"

cache:
  directories:
    - "node_modules"

sudo: required
addons:
  chrome: stable

before_script:
 - xvfb-run make test

 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - pip install --user python-igraph
    
script:
 - ./run_tests.sh
    
