language: node_js
node_js:
 - "node"

cache:
  directories:
    - "node_modules"
    - "$HOME/.cache/pip"

sudo: required
addons:
  chrome: stable
 
before_script:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
 - pip install --user python-igraph
    
script:
 - xvfb-run --server-args="-screen 0 1440x900x24" ./run_tests.sh
    
