language: node_js
node_js:
    - "node"
    
cache:
  directories:
    - $HOME/.cache/pip

before_script:
    - pip install -U pip wheel
    - pip install --user python-igraph

script:
    - ./run_tests.sh
    
