name: PackagePortable

on:
  push:
#    paths-ignore:
#      - 'doc/**'
#      - '**.md'
    tags:
      - "v*.*.*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: install wine
#          wget -nc https://dl.winehq.org/wine-builds/winehq.key
#          sudo apt-key add winehq.key
#          sudo add-apt-repository -y 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
#          sudo DEBIAN_FRONTEND=noninteractive apt install -y --install-recommends winehq-stable wine-stable wine-stable-i386 libfaudio0:i386 libglib2.0-0:i386 libgstreamer-plugins-base1.0-0:i386 libgstreamer1.0-0:i386 libodbc1:i386 libmount1:i386 libselinux1:i386 libpcre2-8-0:i386
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install -y wine64 wine32 libwine:i386 libfaudio0:i386 libglib2.0-0:i386 libgstreamer-plugins-base1.0-0:i386 libgstreamer1.0-0:i386 libodbc1:i386 gstreamer1.0-plugins-good:i386 libblkid1:i386 libasound2:i386 libasound2-data:i386 libfaudio0:i386 libfontconfig1:i386 libfreetype6:i386 libgcc-s1:i386 libgphoto2-6:i386 libgphoto2-port12:i386 libgstreamer-plugins-base1.0-0:i386 libgstreamer1.0-0:i386 liblcms2-2:i386 libldap-2.4-2:i386 libmpg123-0:i386 libc6:i386 libncurses6:i386 libopenal1:i386 libpcap0.8:i386 libpulse0:i386 libtinfo6:i386 libudev1:i386 libunwind8:i386 libvkd3d1:i386 libvulkan1:i386 libx11-6:i386 libxext6:i386 libxml2:i386 ocl-icd-libopencl1:i386 zlib1g:i386 openssl libshout3:i386 libsoup2.4-1:i386 libtag1v5:i386 libavcodec58:i386 libglib2.0-0 libicu66:i386 libwine
        
      - name: checkout
        uses: actions/checkout@v2
        
      - name: run package script
        run: |
          cd ./packaging
          ./package.sh
        
      - name: Archive atompm-portable file
        uses: actions/upload-artifact@v2
        with:
          name: atompm-portable
          path: ./packaging/atompm-portable/atompm-portable.zip
          
#      - name: create release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: ./packaging/atompm-portable/atompm-portable.zip
          
          
          
        
